# -*- mode: python ; coding: utf-8 -*-


block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src', 'src'),
    ],
    hiddenimports=[
        # Standard library
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.scrolledtext',
        'pathlib',
        'json',
        'logging',
        'datetime',
        'threading',
        're',
        'os',
        'sys',
        'hashlib',
        'hmac',
        'base64',
        'collections',
        'statistics',
        'tempfile',
        'csv',
        'io',
        'inspect',
        'importlib',
        # Third-party
        'oracledb',
        'openpyxl',
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.kdf',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.openssl',
        # Core src modules (must be available)
        'src.errors',
        'src.constants',
        'src.logger',
        'src.config_manager',
        'src.excel_handler',
        'src.db_connection',
        'src.data_updater',
        'src.security',
        'src.progress',
        'src.gui',
        # P1 modules
        'src.ora_errors',
        'src.data_source',
        'src.auth',
        'src.cli',
        # P2 modules
        'src.service',
        'src.service.__init__',
        'src.notification',
        'src.history_viewer',
        # P3 modules
        'src.data_compare',
        'src.diagnostics',
        'src.env_config',
        'src.backup_manager',
        'src.scheduler',
        'src.trend_analysis',
        'src.import_stats',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='DBForge',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)